# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Bee's Space
email: web@beeau.net
description: >- # this means to ignore newlines until "baseurl:"
  My personal place on the internet.
minimal_mistakes_skin: "neon"
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Australia/Sydney

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Bee"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "My personal place on the internet. Buzz Buzz."
  links:
    - label: "Discord"
      icon: "fa-brands fa-fw fa-discord"
      url: "https://discordapp.com/users/1405866080882135181"
    - label: "Steam"
      icon: "fa-brands fa-fw fa-steam-symbol"
      url: "https://steamcommunity.com/id/Bee_au/"
    - label: "Roblox"
      icon: "fas fa-fw fa-diamond"
      url: "https://www.roblox.com/users/508425824/profile"

footer:
  links:
    - label: "Discord"
      icon: "fa-brands fa-fw fa-discord"
      url: "https://discordapp.com/users/1405866080882135181"
    - label: "Steam"
      icon: "fa-brands fa-fw fa-steam-symbol"
      url: "https://steamcommunity.com/id/Bee_au/"
    - label: "Roblox"
      icon: "fas fa-fw fa-diamond"
      url: "https://www.roblox.com/users/508425824/profile"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true